### ISSUE TITLE
fugit compile problem

### ISSUE THREAD

**Issue by pdgilbert** [korken89/fugit#16]
One of the last few commits, just prior to release of v0.3.3, has started giving me compile errors
```
   Compiling fugit v0.3.3
error[E0658]: panicking in constants is unstable
  --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/fugit-0.3.3/src/helpers.rs:48:32
   |
48 |     pub const GREATER_EQ: () = assert!(L >= R);
   |                                ^^^^^^^^^^^^^^^
   |
   = note: see issue #51999 <https://github.com/rust-lang/rust/issues/51999> for more information
   = note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)

```
Any ideas?

**Comment by TDHolmes** [comment]
Recent commits have started to use const panic. Update your rust install to newest (1.57 at least I think?)

**Comment by korken89** [comment]
Indeed fugit requires 1.57 att the moment.

**Comment by pdgilbert** [comment]
Thanks, that solved it. Seems like I just updated to 1.56 a few weeks ago. I guess I'm in the fast lane. Got my examples mostly building again with cortex-m-rtic release 1.0.0 (see https://github.com/pdgilbert/rust-integration-testing/actions/runs/1641101680).
