### ISSUE TITLE
short functions which return fixed types

### ISSUE THREAD

**Issue by burrbull** [korken89/fugit#26]
Now we have 2 main ways to create value

1.  `DurarionType::from_ticks(val)` - fixed type result, can be used in any context, but long call
2. `Ext` traits: 1.millis() - generic type result, non-const. Can fail to resolve result type if information is not enough.

Need short variant of 1 which looks similar to 2.
cc @korken89

**Comment by TDHolmes** [comment]
Can you elaborate? I'm not sure I fully understand the request.

Like `1.from_ticks_ms()`?

**Comment by burrbull** [comment]
We have `ExtU32` which give us `millis<NOM, DEMOM>() -> Duration<NOM, DEMOM>`. And in most cases it works very well.
But often it can't detect expected coefs. In those cases simple `millis() -> MillisDuration` would work better.
Example:
```rust
let time: MillisDurationU32 = ...;
if time > 5.millis() { // <- error here: unknown type
   ...
}
```
It would be ideal if Rust could default types in trait methods, but it can't even in nightly.
```rust
trait ExtU32 {
   fn millis<const NOM: u32 = 1, const DENOM: u32 = 1_000>() -> DurationU32<NOM, DEMOM>;
}
```

**Comment by korken89** [comment]
const defaults comes in the next stable if I'm not mistaken, this should be fixable then.

**Comment by korken89** [comment]
It seems my hopes were too high for the new `const generics defaults`, the currently release version is too crippled and one only runs into this wherever one would like to use it:

```
error: defaults for const parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions
   --> src/duration.rs:684:76
    |
684 | impl<const L_NOM: u32, const L_DENOM: u32, const R_NOM: u32 = L_NOM, const R_DENOM: u32 = L_DENOM>
    |                                                                            ^^^^^^^
```

So the questions then is, how to tackle this issue.
For now does this work?

```
let millis = DurarionType::millis(val);
````

**Comment by burrbull** [comment]
I don't see good solve for now.

And yes, now I use `Hertz::MHz(val)`, etc. It is not ideal, but better then nothing.
